org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version = 26.1.2-v1.14
maven_group = net.yeleefff
archives_base_name = enderite-mod

# Dependencies
fabric_api_version=0.148.2+26.1.2